services:
  mysql:
    image: mysql:8.0
    container_name: mysql_task_manager
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: task_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_mvc_app
    command: php -S 0.0.0.0:8000 -t /var/www/html/public
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - ./.env:/var/www/html/.env
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

volumes:
  mysql_data:
    driver: local